openapi: 3.1.0
info:
  title: Описание API сервера проекта «Шесть Городов»
  description: Описание маршрутов сервера проекта.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: "1.0.0"
tags:
  - name: offers
    description: Действия с предложениями.
  - name: favorite
    description: Действия с избранными предложениями.
  - name: premium
    description: Действия с премиальными предложениями.
  - name: user
    description: Действия с пользователем.
  - name: comments
    description: Действия с комментариями.
paths:
  /six-cities/offers:
    get:
      tags:
        - offers
      summary: Список предложений по аренде
      description: Сервис возвращает список из не более 60 предложений по аренде, отсортированный по дате публикации (по убыванию).
        Клиент также может запросить больше предложений, указав нужное количество в параметре запроса.
      responses:
        "200":
          description: Массив предложений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Offer"
        "404":
          description: Предложение не найдено
          content:
            application/json:
              schema:
                type: string
    post:
      tags:
        - offers
      summary: Создание нового предложения
      description: Сервис предоставляет ресурс для создания новых предложений.
        В случае успешного создания предложения сервис в ответе возвращает информацию о созданном предложении.
        Создавать предложения могут только авторизованные клиенты.
      requestBody:
        description: я.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "200":
          description: Объект предложения
          content:
            application/json:
              schema:
                type: string
        "404":
          description: Предложение не найдено
          content:
            application/json:
              schema:
                type: string
  /six-cities/offers/{offerId}:
    get:
      tags:
        - offers
      summary: Детальная информация по предложению
      description: Сервис возвращает детальную информацию по одному предложению с идентификатором `offerId`.
      requestBody:
        description: я.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "200":
          description: Объект предложения
          content:
            application/json:
              schema:
                type: string
        "404":
          description: Предложение не найдено
          content:
            application/json:
              schema:
                type: string
    put:
      tags:
        - offers
      summary: Редактирование предложения
      description: Сервис предоставляет ресурс для редактирования предложения по аренде с идентификатором `offerId`.
        В случае успешного обновления предложения сервис возвращает клиенту обновлённый объект предложения.
        Редактировать предложения по аренде могут только авторизованные клиенты.
      requestBody:
        description: я.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "200":
          description: Объект предложения
          content:
            application/json:
              schema:
                type: string
        "404":
          description: Предложение не найдено
          content:
            application/json:
              schema:
                type: string
    delete:
      tags:
        - offers
      summary: Удаление предложения по аренде
      description: Сервис предоставляет ресурс для удаления предложений по аренде с идентификатором `offerId`.
        Удалять предложения могут только авторизованные клиенты.
  /six-cities/favorite:
    get:
      tags:
        - favorite
      summary: Премиальные предложения для города
      description:  Сервис предоставляет ресурс для получения списка из не более 3 премиальных предложений для определённого города, отсортированный по дате публикации (по убыванию).
      responses:
        "200":
          description: Объект предложения
          content:
            application/json:
              schema:
                type: string
        "404":
          description: Предложение не найдено
          content:
            application/json:
              schema:
                type: string
  /six-cities/premium:
    get:
      tags:
        - premium
      summary: Список избранных предложений
      description: Сервис предоставляет ресурс для получения предложений, добавленных в избранное.
        Ресурс доступен только авторизованным клиентам.
      responses:
        "200":
          description: Объект предложения
          content:
            application/json:
              schema:
                type: string
        "404":
          description: Предложение не найдено
          content:
            application/json:
              schema:
                type: string
  /six-cities/premium/{offerId}:
    patch:
      tags:
        - premium
      summary: Добавление и удаление предложения в/из избранного
      description: Сервис предоставляет ресурс для добавления и удаления любого предложения в/из списка избранных предложений с идентификатором `offerId`.
        Ресурс доступен только авторизованным клиентам.
      requestBody:
        description: я.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "200":
          description: Объект предложения
          content:
            application/json:
              schema:
                type: string
        "404":
          description: Предложение не найдено
          content:
            application/json:
              schema:
                type: string
  /six-cities/sign-up:
    post:
      tags:
        - user
      summary: Создание нового пользователя
      description: Сервис предоставляет ресурс для создания нового пользователя.
        В случае успешного создания пользователя сервис возвращает информацию о созданном пользователе.
  /six-cities/sign-in:
    post:
      tags:
        - user
      summary: Вход в закрытую часть приложения
      description: Сервис предоставляет ресурс для аутентификации и авторизации пользователя.
        Для входа в закрытую часть приложения клиент передаёт логин (email) и пароль пользователя.
        В случае успешной проверки логина и пароля сервис возвращает клиенту токен.
    get:
      tags:
        - user
      summary: Проверка состояния пользователя
      description: Сервис предоставляет ресурс для проверки состояния клиента — авторизован или нет.
        Если клиент авторизован, сервис возвращает соответствующий код состояния и информацию о пользователе
  /six-cities/sign-out:
    post:
      tags:
        - user
      summary: Выход из закрытой части приложения
      description: Сервис предоставляет ресурс для завершения пользовательского сеанса.
  /six-cities/comments/{offerId}:
    get:
      tags:
        - comments
      summary: Список комментариев для предложения
      description: Сервис возвращает список из не более 50 комментариев для определённого предложения, отсортированный по дате публикации (по убыванию).
    post:
      tags:
        - comments
      summary: Добавление комментария
      description: Сервис предоставляет ресурс для добавления комментариев к определённому предложению по аренде.
        Добавлять комментарии могут только авторизованные клиенты.
        В случае успешного добавления комментария сервис возвращает информацию о созданном комментарии.
components:
  schemas:
    Offer:
      type: object
      properties:
        title:
          type: string
          example: Loft Studio in the Central Area
        description:
          type: string
          example: Peaceful studio in the most wanted area in town.
        date:
          type: date-time
          example: 2022-01-18T17:36:34.064Z
        city:
          $ref: "#/components/schemas/City"
        previewImage:
          type: string
          example:
        images:
          type: array
        isPremium:
          type: boolean
          example:
        isFavorite:
          type: boolean
        rating:
          type: number
        type:
          type: string
          enum:
            - "apartment"
            - "house"
            - "room"
            - "hotel"
        bedrooms:
          type: number
        maxGuests:
          type: number
        price:
          type: number
        goods:
          type: array
        host:
          $ref: "#/components/schemas/User"
        comments:
          type: number
        location:
          $ref: "#/components/schemas/Location"
    User:
      type: object
      properties:
        name:
          type: string
          example: Jim
        email:
          type: string
          example: keks@htmlacademy.ru
        avatar:
          type: string
        password:
          type: string
        isPro:
          type: boolean
    City:
      type: object
      properties:
        name:
          type: string
          enum:
            - "Paris"
            - "Cologne"
            - "Brussels"
            - "Amsterdam"
            - "Hamburg"
            - "Dusseldorf"
        location:
          $ref: "#/components/schemas/Location"
    Location:
      type: object
      properties:
        latitude:
          type: number
          example: 50.916361
        longitude:
          type: number
          example: 6.944974
